name: deploy-ai
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: deploy-to-server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: 22
        command_timeout: 30m
        script: |
          set -e 
          cd /var/www/html/python/ocr-ai
          git checkout add-ocr-admin
          git pull origin add-ocr-admin
          uv sync
          cd /var/www/html/python/ocr-ai/ocr-expediente
          pm2 restart 0
          sudo systemctl restart nginx
