name: deploy-ai
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: deploy-to-server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: 22
        command_timeout: 30m
        script: |
          set -e 
          cd backend-monorepo
          git checkout deployment
          git pull origin deployment
          sudo docker-compose down
          sudo docker-compose up -d --build
          sudo docker image prune -f
